### ISSUE TITLE
The search breaks

### ISSUE THREAD

**Issue by pigeonflight** [nomedeusuariodesconhecido/info3180-exam#3]
I've attached an animated gif to explain.
![emailqueryerror](https://cloud.githubusercontent.com/assets/31827/9590589/399a127e-4ffb-11e5-8899-a6ad96b1efde.gif)

**Comment by pigeonflight** [comment]
I see that the query works when you put "Allan Angus".
But if fails for "Allan", "Angus", "Allan A" etc..

**Comment by nomedeusuariodesconhecido** [comment]
Indeed, for simplicity and in the interest of time, the app was designed in this manner.
The intent was to ensure that the fundamental objectives were accomplished.

**Comment by pigeonflight** [comment]
It needs to be fixed though.

**Comment by nomedeusuariodesconhecido** [comment]
I've added code to handle scenario where the name entered in the search bar does not exist in the database.

I acknowledge that this application may be far more robust. sporting capabilities such as Form Validation, Regular Expressions for more forgiving data entry and even htmlentities for escaping special characters for database security. However, in the interest of time and to the end of accomplishing the fundamental objectives of the task, I will defer adding these features for a later date when I will extend the app on my own time as a personal skills development project.

This should address Issue 3 which I will now close, with your acquiescence.

See the app live here: https://info3180-nomedeusuario.c9.io/

**Comment by pigeonflight** [comment]
That's fine.

**Comment by pigeonflight** [comment]
Actually it needs to match partial matches. It should only say "sorry" when there is no user that matches or part matches. I don't need escaping for this.

**Comment by nomedeusuariodesconhecido** [comment]
![4](https://cloud.githubusercontent.com/assets/8847663/9647180/02c0669e-51a0-11e5-8564-e74f0e53fd4c.gif)

This update should resolve the issue.

See the app live here: https://info3180-nomedeusuario.c9.io/

**Comment by pigeonflight** [comment]
I think you're approaching this based on what is convenient/expedient rather than being empathetic to the end user. If you were an end user you would be horrified that typing "all" would not allow you to find Allan, or typing "Glax" wouldn't find someone with the last name "Glaxon".

**Comment by nomedeusuariodesconhecido** [comment]
I can't help but to find some amusement in the denouement of the last few day's plot, for it has taken some interesting twists.

While I am very sensitized to the importance of User Experience goals and am myself quite sympathetic to the cause of designing for optimal Human Computer Interaction, I believe that based upon my understanding of the original objectives of the task, these aforementioned "nicities" would have been of secondary priority to demonstrating basic functionality. I feel, Mr. Bain, that perhaps some NEW objectives, though subtle, might have been now introduced into this task. 

I say all this to say that, had I had a clear understanding of these objectives from the beginning, you can be assured that they would have been accomplished from the on-set. 

That said, I will be diligent in seeing to adjustments that will address the concern you've raised.

**Comment by nomedeusuariodesconhecido** [comment]
The code that addresses this last issue had always been inside the source, however it was commented out. Just a little adjustment corrected that. 

![5](https://cloud.githubusercontent.com/assets/8847663/9666198/50fad584-523a-11e5-96c3-12a94b097321.gif)

Please see the app live here: https://info3180-nomedeusuario.c9.io/

**Comment by pigeonflight** [comment]
now we're talking :+1:
